billi:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  head_body_position_controller:
    type: effort_controllers/JointPositionController
    joint: head_body
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_hand_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_hand
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_leg_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_leg
    pid: {p: 100.0, i: 0.01, d: 10.0}

  left_hand_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_hand
    pid: {p: 100.0, i: 0.01, d: 10.0}
  left_leg_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_leg
    pid: {p: 100.0, i: 0.01, d: 10.0}
  lower_upper1_position_controller:
    type: effort_controllers/JointPositionController
    joint: lower_upper1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  lower_upper2_position_controller:
      type: effort_controllers/JointPositionController
      joint: lower_upper2
      pid: {p: 100.0, i: 0.01, d: 10.0}
  lower_upper3_position_controller:
      type: effort_controllers/JointPositionController
      joint: lower_upper3
      pid: {p: 100.0, i: 0.01, d: 10.0}
  lower_upper4_position_controller:
      type: effort_controllers/JointPositionController
      joint: lower_upper4
      pid: {p: 100.0, i: 0.01, d: 10.0}
