base: base_link
left_front:
<<<<<<< HEAD
 # - lf_hip_link
=======
  - lf_hip_link
>>>>>>> champ
  - lf_upper_leg_link
  - lf_lower_leg_link
  - lf_foot_link

right_front:
<<<<<<< HEAD
  #- rf_hip_link
=======
  - rf_hip_link
>>>>>>> champ
  - rf_upper_leg_link
  - rf_lower_leg_link
  - rf_foot_link

left_hind:
<<<<<<< HEAD
  #- lh_hip_link
=======
  - lh_hip_link
>>>>>>> champ
  - lh_upper_leg_link
  - lh_lower_leg_link
  - lh_foot_link

right_hind:
<<<<<<< HEAD
  #- rh_hip_link
=======
  - rh_hip_link
>>>>>>> champ
  - rh_upper_leg_link
  - rh_lower_leg_link
  - rh_foot_link